// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateSubscriptionsHandlerFunc turns a function with the right signature into a create subscriptions handler
type CreateSubscriptionsHandlerFunc func(CreateSubscriptionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateSubscriptionsHandlerFunc) Handle(params CreateSubscriptionsParams) middleware.Responder {
	return fn(params)
}

// CreateSubscriptionsHandler interface for that can handle valid create subscriptions params
type CreateSubscriptionsHandler interface {
	Handle(CreateSubscriptionsParams) middleware.Responder
}

// NewCreateSubscriptions creates a new http.Handler for the create subscriptions operation
func NewCreateSubscriptions(ctx *middleware.Context, handler CreateSubscriptionsHandler) *CreateSubscriptions {
	return &CreateSubscriptions{Context: ctx, Handler: handler}
}

/*CreateSubscriptions swagger:route POST /subscriptions subscriptions createSubscriptions

Create a subscription

*/
type CreateSubscriptions struct {
	Context *middleware.Context
	Handler CreateSubscriptionsHandler
}

func (o *CreateSubscriptions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateSubscriptionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
