// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSubscriptionByIDParams creates a new GetSubscriptionByIDParams object
// no default values defined in spec.
func NewGetSubscriptionByIDParams() GetSubscriptionByIDParams {

	return GetSubscriptionByIDParams{}
}

// GetSubscriptionByIDParams contains all the bound params for the get subscription by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters getSubscriptionById
type GetSubscriptionByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The id of the subscription to retrieve
	  Required: true
	  In: path
	*/
	SubscriptionID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetSubscriptionByIDParams() beforehand.
func (o *GetSubscriptionByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rSubscriptionID, rhkSubscriptionID, _ := route.Params.GetOK("subscriptionId")
	if err := o.bindSubscriptionID(rSubscriptionID, rhkSubscriptionID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSubscriptionID binds and validates parameter SubscriptionID from path.
func (o *GetSubscriptionByIDParams) bindSubscriptionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.SubscriptionID = raw

	return nil
}
