// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListSubscriptionsHandlerFunc turns a function with the right signature into a list subscriptions handler
type ListSubscriptionsHandlerFunc func(ListSubscriptionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListSubscriptionsHandlerFunc) Handle(params ListSubscriptionsParams) middleware.Responder {
	return fn(params)
}

// ListSubscriptionsHandler interface for that can handle valid list subscriptions params
type ListSubscriptionsHandler interface {
	Handle(ListSubscriptionsParams) middleware.Responder
}

// NewListSubscriptions creates a new http.Handler for the list subscriptions operation
func NewListSubscriptions(ctx *middleware.Context, handler ListSubscriptionsHandler) *ListSubscriptions {
	return &ListSubscriptions{Context: ctx, Handler: handler}
}

/*ListSubscriptions swagger:route GET /subscriptions subscriptions listSubscriptions

List all subscriptions

*/
type ListSubscriptions struct {
	Context *middleware.Context
	Handler ListSubscriptionsHandler
}

func (o *ListSubscriptions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListSubscriptionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
