// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Factom Live API

    Schemes:
      http
    Host: liveapi.factom.com
    BasePath: /v1
    Version: 0.0.1
    License: MIT

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
